name: mypipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Build running"
          sleep 30
      - name: second step or task
        run: |
          echo "Build completed"
          sleep 30
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Test running"
          sleep 30
      - name: second step or task
        run: |
          echo "Test completed"
          sleep 30 

